"""
02b_evaluate_cude_nn.jl

Evaluate trained cUDE candidate models on the MIMIC-IV validation/test cohort
generated by step 00.

Pipeline:
1. Load shared helpers and workflow configuration.
2. Resolve step 00 cohort inputs, step 02a model artifacts, and step 02b outputs.
3. Load the MIMIC-IV training and validation/test cohorts without re-running preprocessing.
4. Evaluate each configured cUDE width/model candidate with patient-level multi-start fitting.
5. Save patient metrics, optimized parameters, plots, and model summaries for step 02c.

Command line:
    JULIA_NUM_THREADS=auto julia --project=. scripts/02b_evaluate_cude_nn.jl

Use `config/workflow_config.jl` to switch between `results/` and
`results_test/`, change widths/model indices, or disable progress bars.
"""

# =============================================================================
# IMPORTS AND SHARED HELPERS
# Minimal dependencies used directly by this executable workflow script.
# =============================================================================

using Dates
using DataFrames: nrow
using Logging
using Base.Threads: nthreads

include(joinpath(@__DIR__, "..", "src", "data_io.jl"))
include(joinpath(@__DIR__, "..", "src", "models.jl"))
include(joinpath(@__DIR__, "..", "src", "fitting.jl"))
include(joinpath(@__DIR__, "..", "src", "plotting.jl"))
include(joinpath(@__DIR__, "..", "config", "workflow_config.jl"))

# =============================================================================
# SCRIPT SETTINGS
# User-editable settings live in `config/workflow_config.jl`.
# =============================================================================

config = WORKFLOW_CONFIG
settings = config.cude_evaluation
dataset_config = config.datasets[settings.dataset_key]

# =============================================================================
# INPUT PATHS
# Step 02b consumes step 00 cohorts and step 02a trained cUDE artifacts.
# =============================================================================

cohort_dir = config.outputs.cohorts
training_input_dir = settings.training_input_dir
dataset_name = dataset_config.dataset_name

# =============================================================================
# OUTPUT PATHS
# Files and folders produced by this run.
# =============================================================================

output_root = settings.output_dir

# =============================================================================
# DERIVED SETTINGS
# Values derived from config and loaded artifacts. No heavy side effects here.
# =============================================================================

dataset_name == "MIMIC-IV" ||
    error("Step 02b currently evaluates only the MIMIC-IV validation/test split. Got dataset=$(dataset_name).")

config.model.t_scale == T_SCALE ||
    error("cUDE evaluation currently requires config.model.t_scale=$(config.model.t_scale) to match models.jl T_SCALE=$(T_SCALE).")

widths = settings.widths
model_indices = settings.model_indices
workflow_output_paths = (
    cohorts=cohort_dir,
    cude_training=training_input_dir,
    cude_evaluation=output_root,
)

# =============================================================================
# PIPELINE
# Linear workflow execution.
# =============================================================================

@info "cUDE evaluation workflow started at $(now())."
log_workflow_context(
    config;
    script_name=basename(@__FILE__),
    output_paths=workflow_output_paths,
)

ensure_output_dirs!(output_root; header="Ensured step 02b output root")

@info "Loading preprocessed $(dataset_name) cohort from step 00."
cohort = load_preprocessed_cohort(dataset_name, cohort_dir)
training_dataset = cohort.training
validation_dataset = cohort.test
training_ids = [patient.id for patient in training_dataset]

@info "Dataset: $(dataset_name)"
@info "Training patients: $(length(training_dataset))"
@info "Validation/test patients: $(length(validation_dataset))"
@info "Configured widths: $(collect(widths))"
@info "Configured model indices: $(collect(model_indices))"
@info "Julia threads: $(nthreads())"

for width in widths
    @info "Starting cUDE evaluation for $(dataset_name), width=$(width)."

    width_paths = cude_evaluation_width_output_paths(output_root, width, dataset_name)
    ensure_output_dirs!(
        (width_dir=width_paths.width_dir,);
        header="Ensured cUDE evaluation output directory for width $(width)",
    )

    artifacts = load_cude_training_artifacts(training_input_dir, width)
    n_candidates = length(artifacts.neural_network_parameters)
    length(artifacts.ode_params) == n_candidates ||
        error("Mismatched cUDE artifacts for width $(width): $(n_candidates) neural candidates and $(length(artifacts.ode_params)) ODE parameter vectors.")

    chain = neural_network_model(settings.nn_depth, width; input_dims=settings.input_dim)
    summary_rows = Any[]

    for model_idx in model_indices
        1 <= model_idx <= n_candidates ||
            error("Configured model_idx=$(model_idx) is outside available candidates 1:$(n_candidates) for width $(width).")

        @info "Evaluating $(dataset_name) cUDE candidate width=$(width), model=$(model_idx)."

        paths = cude_evaluation_model_output_paths(output_root, width, model_idx, dataset_name)
        ensure_output_dirs!(
            (eval_dir=paths.eval_dir, profiles=paths.profiles_dir);
            header="Ensured cUDE evaluation output directories for width $(width), model $(model_idx)",
        )
        log_output_paths(
            (
                best_params=paths.best_params,
                patients_params_train=paths.patients_params_train,
                patients_params_val=paths.patients_params_val,
                patients_metrics_val=paths.patients_metrics_val,
                correction_function=paths.correction_function,
                summary=paths.summary_csv,
            );
            header="cUDE evaluation output files for width $(width), model $(model_idx)",
        )

        neural_params = artifacts.neural_network_parameters[model_idx]
        training_log_params = Vector(artifacts.ode_params[model_idx])
        pguess_stats = median_log_parameter_guess(training_log_params; n_params=settings.n_params)
        pguess = pguess_stats.pguess

        @info "Selected cUDE evaluation pguess for width=$(width), model=$(model_idx): $(exp.(pguess))"
        @info "Training parameter median [Q1-Q3] for width=$(width), model=$(model_idx): $(pguess_stats.median_natural) [$(pguess_stats.q1_natural), $(pguess_stats.q3_natural)]"

        save_cude_correction_function_plot(
            paths.correction_function,
            chain,
            neural_params;
            t_scale=config.model.t_scale,
            plotting=settings.plotting,
            display_plot=settings.display_plots,
        )

        params_extraction(
            training_dataset,
            training_log_params;
            N_params=settings.n_params,
            data_label="training",
            dataset=dataset_name,
            figsave_path=paths.eval_dir,
            show_outliers=true,
            savefigure=settings.plotting,
            show_progress=settings.progress_bars,
        )

        evaluation = evaluate_cude_model(
            validation_dataset,
            chain,
            neural_params,
            pguess,
            settings;
            dataset_name=dataset_name,
            width=width,
            model_idx=model_idx,
        )

        if isempty(evaluation.successful_patients)
            @warn "No successful patients for $(dataset_name), width=$(width), model=$(model_idx). Skipping artifact export and summary row."
            continue
        end

        for (patient, result) in zip(evaluation.successful_patients, evaluation.results)
            save_cude_patient_plots(
                result.sol,
                patient,
                dataset_name,
                paths.profiles_dir;
                plotting=settings.plotting,
                display_plots=settings.display_plots,
            )
        end

        params_extraction(
            evaluation.successful_patients,
            evaluation.ode_params_val;
            N_params=settings.n_params,
            data_label="validation",
            dataset=dataset_name,
            figsave_path=paths.eval_dir,
            show_outliers=true,
            savefigure=settings.plotting,
            show_progress=settings.progress_bars,
        )

        saved = save_cude_evaluation_artifacts(
            paths;
            training_ids=training_ids,
            training_log_params=training_log_params,
            validation_ids=evaluation.patient_ids,
            validation_log_params=evaluation.ode_params_val,
            smapes=evaluation.smape_values,
            rmsles=evaluation.rmsle_values,
            losses=evaluation.loss_values,
            n_params=settings.n_params,
        )

        model_id = "cfg$(settings.nn_depth)$(width)_$(model_idx)"
        push!(
            summary_rows,
            cude_model_summary_row(
                model_id=model_id,
                model_idx=model_idx,
                nn_depth=settings.nn_depth,
                nn_width=width,
                losses=evaluation.loss_values,
                smapes=evaluation.smape_values,
                rmsles=evaluation.rmsle_values,
            ),
        )

        @info "Saved cUDE evaluation width=$(width), model=$(model_idx): $(nrow(saved.metrics)) patient rows."
    end

    summary_df = write_cude_model_summary(width_paths.summary_csv, summary_rows)
    @info "Saved cUDE model summary for $(dataset_name), width=$(width): $(nrow(summary_df)) rows."
    @info "Completed cUDE evaluation for $(dataset_name), width=$(width)."
end

@info "cUDE evaluation workflow ended at $(now())."
